:imagesdir: ../../assets/images
include::../style.adoc[]

== Lab Environment Details 

This is a fully guided workshop All necessary links, credentials, access details, and configurations are provided exactly when and where they are needed. No prior setup is required, as everything needed to complete the exercises is fully documented (ツ)

A number of components are preconfigured to enable the execution of this entire workshop within a short timeframe. We will discuss each of this throughout the course of this workshop.

== Prepare your workshop environment

You will need to access the web terminals and Dev Spaces to apply configuration

. Login to both the terminals on the right side using the following command.

+
[source,sh,role="execute",subs=attributes+]
----
oc login -u admin -p {ocp_cluster_openshift_cluster_admin_password} https://172.30.0.1:443
----
. Type `y` when your are prompted with *Use insecure connections? (y/n):*
. You should see a `Login successful.` message

== OpenShift



== Devspaces

