= Intelligent coding: Building a code assistant with Red Hat Enterprise Linux AI

:experimental: true
:imagesdir: ../assets/images
:toc: false
:numbered: true

[#code_activity]
== Coding With AI

During this portion of the lab, we are going to use AI to build real computer programs! Crazy, right? Even if you're not a coder, don't worry, you're gonna do great.

=== Game Time

We are going to build some short and sweet (and fun) game programs from scratch! 

You will have 3 game options to choose from to start building. You **do not** have to complete all 3 activities, and you **do not** need to work on them in any particular order. 

As you build the games, you will have the option to work in the following languages:

* Bash
* Python

If you choose to work in other languages, by all means! However, I will only provide templates, working scripts and execution instructions for Python and Bash for our games. Our RHEL machines are also limited in terms of what we can execute unless you install additional packages. 

We have template scripts with instructions for you to follow as comments in the files. Let's get working.

==== Accessing the activity files

We already have the GitHub repo cloned to our machine with the necessary files. 

Inside of **VSCode**, go to `File` -> `Open Folder`, and navigate to the rhone_code folder which will be at the following path:

[source,console]
----
/home/dev/rhone_code/
----

Now, from the left-hand side Explorer, open the `code_files` folder.

Select the game file of your preference, in the language of your choice. (feel free to do multiple!) Open the files you want to work on in the VS Code editor.

==== Game Summaries

. **Rock Paper Scissors**: Play rock, paper, scissors against the computer!
. **Word Scramble**: The program scrambles a word and the user has to guess what it is.
. **Simple Quiz Game**: The program asks a few trivia questions and then gives a final score.

==== Get to Coding!

Follow the guidance in the game building activity files. Instructions for each game, including different ways to use the Continue extension are within the comments of the files. Once finished, your file will become your executable game application. 

IMPORTANT: Ensure any text that does not contribute to the game code stays as a comment. You will build out the application code in the second half of the files.

**Experiment with other models and various Continue functions while coding**

* Ensure you are experimenting with the various models available to you whilst coding your game!

**Switching models in RHEL AI**

We suggest experimenting with the Qwen model in RHEL AI in addition to the Granite model. To switch models, you will stop serving the Granite model first by typing kbd:[CTRL] + kbd:[C].

Once the serving process properly stops, you may now serve the Qwen model:

[source,console,role=execute,subs=attributes+]
----
ilab model serve --model-path ~/.cache/instructlab/models/Qwen/Qwen2.5-7B-Instruct --gpus 1 -- --max-model-len 5000
----

At this point, the configuration for the Qwen model will now work in VSCode, and the Granite model will no longer work.

==== Testing (and playing) Your Game

Once you've completed the coding activities, save your file(s) that you wish to test.

We will use the Terminal capability within VSCode to test our applications. To open a terminal session navigate to `Terminal` -> `New Terminal` in the top navigation bar of the VSCode app. Or you may press kbd:[CTRL] + kbd:[`].

Navigate to the directory within which the file you wish to execute is saved.

Example:

[source,console]
----
cd /home/dev/rhone_code/game_templates/rock_paper_scissors/
----

Please follow the following instructions depending on your chosen language.

==== If you are using Python (.py)

Run the following command (substitue your filename):

[source,console]
----
python your_filename.py
----

==== If you are using Bash (.sh)

Make the file executable (you only need to do this once). Substitute your filename:

[source,console]
----
chmod +x your_filename.sh
----

Run the following command (substitue your filename):

[source,console]
----
./your_filename.sh
----

==== Troubleshooting Tips and Reminders

**If you see a "command not found" or "permission denied" error**:

* Double-check the file name is spelled correctly

* Make sure you’re in the correct directory (ls to list files)

* For .sh files, try bash yourfile.sh if ./yourfile.sh doesn't work

**Other error or application isn't working as expected**:

* Use your code assistant to help you debug

* Feed the errors or explain any issues in the chat and have the AI help you correct your code

=== Optional: Game Solutions

If you had some trouble getting your game to work and/or you would like to see what working code can look like, navigate to the following directory in your VSCode setup (where you should have the entire cloned repository in view in the `Explorer` tab):

[source,console]
----
~/rhone_code/game_solutions/
----

Use the execution instructions in the above sections to run the code for any of the provided game programs!

[cols="2*", frame=none, grid=none]
|===
| xref:03-vscode.adoc[← Setting up Visual Studio Code]
| xref:05-conclusion.adoc[Next → Conclusion]
|===
