:imagesdir: ../../assets/images
include::style.adoc[]

== Safeguarding Application Connectivity for the Hybrid Cloud

== Overview

Hybrid cloud environments offer flexibility and scalability, but they also introduce significant security and connectivity challenges. In this workshop, we'll guide you through the process of safeguarding and connecting your hybrid cloud environments with Red Hat. You'll learn how to:

* Implement and manage consistent security policies across multiple clusters.
* Empower developers to independently manage their application connectivity with self-service guardrails.
* Connect services running on different platforms and clouds, as well as infrastructure that's inaccessible over the network.
* Expose and consume services both within and outside your organization.


Through hands-on exercises, you'll gain practical experience in using *Red Hat Connectivity Link*, *Red Hat Service Interconnect*, and *Red Hat OpenShift Service Mesh* to address these challenges and improve your hybrid cloud infrastructure's security and reliability.


== Application Connectivity


=== What is Application Connectivity?

=== Business Challenges with Hybrid Cloud

=== A three-pronged approach


== Workshop Modules

