:imagesdir: ../../assets/images/m1
include::style.adoc[]

== Safeguarding Application Connectivity for the Hybrid Cloud

== Overview

Hybrid cloud environments offer enterprises with flexibility, scalability, and agility, but they also introduce significant connectivity and security challenges. Organizations must ensure systems and services can communicate effectively, securely and seamlessly - across on-premises, private, and public clouds

A few of the challenges include

* Fragmented app connectivity
* Drift in configuration across multiple environment
* Insufficient security policy in application communications
* Mismanagement of resources
* Lack of visibility across hybrid  infrastructures

== Enabling secure app connectivity 

In this workshop, we will guide you through Red Hat's connectivity solutions that can help enterprises secure and manage hybrid cloud application connectivity. Through a real-world enterprise scenario, you will learn how to:

* Securely connect services running on different platforms and clouds, without VPNs or complex networking.
* Safely expose and consume services both within and outside your organization.
* Enforce authorization policies to restrict service-to-service communication without modifying application code, even within the same cluster
* Implement and manage consistent security policies across multiple clusters through GitOps
* Empower developers to independently manage their application connectivity with self-service guardrails.

Through hands-on exercises, you'll gain practical experience in using  *{rhcl}*, *{rhsi}*, and *{rhossm}* to address these challenges and improve your hybrid cloud infrastructure's security and reliability.